### PR TITLE
Clarify varnish_version lookup, process grace-* options, etc

### PR DESCRIPTION
**Pull request by jean**

### CODE REVIEW

**Comment by jean** [comment]
The build failure is due to an unrelated setuptools version conflict.

**Comment by jean** [comment]
The failure is still `VersionConflict: (setuptools 12.0.5 (/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages), Requirement.parse('setuptools==0.6c11'))`
@jensens do you think this can be merged?

**Comment by jensens** [comment]
i fixed master travis cfg to not use bootstrap anymore and unset version pins, now it runs at least.

**Comment by jean** [comment]
Hi @jensens .. I see it's still showing the failed build, can a new build be triggered without a dummy commit?

**Comment by jensens** [comment]
can you rebase with master please?

**Comment by jean** [comment]
@gforcada thanks for the nudge, I lost track of this tab ..

**Comment by jean** [comment]
varnish doesn't get built:

```
Expected: 
    Installing varnish. Installing varnish-build.  
    varnish-build: Downloading ...  
    varnish-build: Unpacking and configuring 
    ...

Got: 
    Not found: /tmp/tmphTkkMzbuildouttests/zc.recipe.cmmi/ 
    Not found: /tmp/tmphTkkMzbuildouttests/zc.recipe.cmmi/
```

**Comment by jean** [comment]
@fredvd the build is green

**Comment by jensens** [comment]
manually merged, for some reason auto-merge had problems...

**Pull request closed without merging**
