### PR TITLE
add options for probe settings

### PR DESCRIPTION
**Pull request by frisi**
especially needed when using a load balancer as backend that needs
smaller window and threshold to recognice a sick backend earlier

### CODE REVIEW

**Comment by frisi** [comment]
@fredvd hey fred. picked you as reviewer  as you're one of the last commiters. if you'd like somebody else to review that please re-assign or let me know ;-)

**Comment by erral** [comment]
Useful indeed

**Comment by frisi** [comment]
@erral we're using haproxy behind varnish too. and if you use grace-sick/healthy combined with only one backend (namely a load balancer) the default timeout/window are not the best choice. this is why i came up with this PR ;-)

**Comment by frisi** [comment]
thanks for your review/merging @fredvd 
will you make a 6.0.0rc1 or  6.0.0 release. i guess more than a hand full of people are using this on production

**Comment by fredvd** [comment]
@erral @frisi Are you using haproxy later than 1.5.X ? I'm still stuck on that version because of the completely changed and complex syntax with sticky sessions in later versions.  Would love to see an example config of that.  Or did you drop sticky session support?

**Comment by fredvd** [comment]
I'll relase a 6.0.0b2 now.  There's some small stuff left before this shoul be final. 

>  i guess more than a hand full of people are using this on production

I asked exactly this at the PloneTagung in Dresden this March in front of 50+people. Almost everybody knows about the recipe, but none use it in production. Most people use the generated varnish.vcl  . Or maybe that was a very much skewed representation with a lot of higher education customers an core developer who know what theyr're doing. :-P

**Comment by fredvd** [comment]
@frisi released 6.0.0b2

**Comment by erral** [comment]
We are using haproxy 2.1.3 using plone.recipe.haproxy in production with python3. We are using this template to create the haproxy configuration, it is based on a previous template for an older haproxy https://github.com/codesyntax/bobtemplates.cs/blob/master/bobtemplates/cs/cs_plone_buildout/templates/haproxy.tpl.bob

**Pull request merged**
