### PR TITLE
user option fix for varnish 4.1

### PR DESCRIPTION
**Pull request by petschki**
see #35

### CODE REVIEW

**Comment by frisi** [comment]
your changes look good @petschki - thanks for tackling this ticket.
i'd use string.format for variable subsitutions as it conforms new style guidlines and is more readable.
```python
print >>tf, '    -j unix,user=%s,ccgroup=%s \\' % (
                            self.options['user'], self.options['group'])
print >>tf, '    -j unix,user={user},ccgroup={group} \\'.format(**self.optoins)
```

on the other hand the whole method has a todo comment that it needs refactoring `# XXX TODO: refactor me! make this a template.`

great to have this recipe ready to generate varnish4.1 compatible start-scripts!

**Comment by jensens** [comment]
We need really get rid of this `print >>tf`` lines, but this is out of scope of this PR (except if you want some extra exercise @petschki).

I agree with @frisi about the string formatting method. 

Overall fine and a good improvement! Thanks!

**Comment by petschki** [comment]
I'm willing to put my jinja ninja power in a startscript template in a separate pull request instead of  changing all the string formatters here ... 🥋

**Comment by frisi** [comment]
> I'm willing to put my jinja ninja power in a startscript template in a separate pull request instead of changing all the string formatters here ...

great. ask miko for his arnhem-bingo-catana-blade if you need the right tool for this task

**Comment by petschki** [comment]
@miohtama ⚔︎
@jensens please merge, otherwise this conversation gets crazy ...

**Pull request merged**
