### PR TITLE
Minimal fix the bugs & vulnerabilities

### PR DESCRIPTION
**Pull request by cleberjsantos**
Pinning this versions, fix the bugs & vulnerabilities:

- [VSV00001 DoS vulnerability](https://varnish-cache.org/security/VSV00001.html)
- [VSV00002 Data leak - ‘-sfile’ Stevedore transient objects](https://varnish-cache.org/security/VSV00002.html)

### CODE REVIEW

**Comment by cleberjsantos** [comment]
@mauritsvanrees Yeah, it's breaking with the requirement 'six', but I see you've adjusted it on the master.

**Comment by mauritsvanrees** [comment]
Now I'm confused. I assumed this was already meant to go to the master branch. Did I see this wrong? Did you first want to merge this to the varnish-5 branch? I didn't notice this. Sorry to steer you in the wrong direction.

The commits looked fine for master, except that a few minutes before you did these changes, I made changes on master to fix the `six` version number so Travis worked. 

Let me try your commits in a new pull request.

If you want to work on the varnish-5 branch (pull request #38) then I think there are several conflicts that have to be solved first, because various changes have been done on master since that branch was created.

**Comment by mauritsvanrees** [comment]
Oh, I see that for master the only change needed is to update 4.1 to 4.1.9. I have done so in https://github.com/collective/plone.recipe.varnish/pull/53.

I will change the base of your PR back to varnish-5.

**Comment by mauritsvanrees** [comment]
Actually, I cannot change the base.
O, but I can merge it manually to the collective/varnish-5 branch. Done.
The tests on that branch will still fail, and the branch needs work. But so far: thank you.

**Comment by cleberjsantos** [comment]
Tks, I'm going to revise this varnish-5 branch, I think it's been a while since it's updated, and then after testing start the changes to send the pull request.

**Pull request closed without merging**
