### PR TITLE
run the purge when entering the vcl_hit state

### PR DESCRIPTION
**Pull request by erral**
When debugging some varnish issues in a client's website, we have found that our varnish (configured with the defaults provided by the recipe) **never** purged its contents when requested to do so.

After some trials and errors we found that changing the order of the `PURGE` method checking in vcl_hit fixes most of the issues.

According to our debugging session with varnishlog, a `PURGE` request is _in esence_ a `GET` request with a special `PURGE` marker, but it's treated like a `GET`. So Varnish enters the `vcl_hit` method and the first thing it checks is if the object is in the cache (`obj.ttl > 0`) and if so returns it.

Replacing the order of the `PURGE` check we purge the object and guarantee that the next access will be a `MISS` which we think is the intended feature even before of checking if the object is in the cache.

This PR will be followed by a couple of PRs in plone.app.caching and plone.cachepurging regarding the `PURGE` requests missing the `Host` header to let Varnish know what should it purge.

@aitzol @libargutxi

### CODE REVIEW

**Comment by jensens** [comment]
Good catch!

**Comment by fredvd** [comment]
@erral We found the same problem with purging a few months ago. Meanwhile while trying to fix these and other small issues I concluded that the setup of the recipe has become way too complicated for multiple reason. I have created a separate branch were all support for earlier versions and different templates and varnish_version has been removed, it tries to configure only the 6.0.X LTS version. See

https://github.com/collective/plone.recipe.varnish/tree/support_varnish_lts

The ticket for it is this one: https://github.com/collective/plone.recipe.varnish/issues/70

Varnish software is releasing Varnish every half year now, and they cherry pick a new lts version only when a released version has been proven 'stable' in the field, It's no longer doable for a small community like ours to keep the recipe up to date for the normal releases.

Specifically the purging was broken because a new syntax/config for Varnish 5.X purging was introduced to plone.recipe.varnish with features switches, based on documentation from the Varnish blog, but the feature switch checked on varnish_version which enabled the alternative purge buggishly also on Varnish 6 where, from what I have tested so far the documentation from Varnish 6 is not working at all.

I have filed a bug report for this at the varnish-cache github repo, but so far the only response has been that their varnishtest suite tests this feature and the tests work. From my limited understanding their tests only test for a certain http status as response but they don't test if something actually got purged.  To be continued...

So the support_varnish_lts branch has the 'smart' purging removed and uses the default purging strategy again.  And the other issue was the hostname being pushed into the lookup hash, which is unnecessary for Plone deployment because the hostname is in the VirtualHostMonster rewrite.  

See: https://github.com/collective/plone.recipe.varnish/issues/64

I have the lts branch recipe running in production now for a while with the following configuration where I override the vcl_hash function:

```
[varnish-configuration]
recipe = plone.recipe.varnish:configuration
backends = 127.0.0.1:${conf:varnish_next}
vcl-version = 4.1
vcl_hash =
       hash_data(req.url);
       return(lookup);
```

The question at the end of issue 64 is if we shouldn't make this the default behavior.

I've been a little time constrained the last 2 months. I chatted with Jens and some others about the varnish LTS issues and to support the LTS only At PloneConf. Did some more polishing, but should have pushed this early to a beta releases to avoid double work and more bug hunting by others like you, my apologies.

**Comment by fredvd** [comment]
I’ll try to look at this branch this afternoon to understand your improvements.

My first hunch is that it is unnecessary to modify plone.app.cachinf and plone.cachepurging to inject the host header. We will only add more possible breaking points and complexity when the host header as detected by Plone is incorrect. 

Not putting host into the varnish hash so that the purge command doesn’t have to provide the correct host is imho ‘easier’

**Comment by erral** [comment]
Thank you for your answer @fredvd we were looking indeed at #64 too...

Regarding the changes p.a.caching and p.cachepurging, I will keep them on hold then. Some time ago (sorry, I can't find the reference right now), we found documentation regarding the cache purging in Varnish which said that we needed to send also the `Host: xxxx` header in the purge request. We took that approach last week when testing our setup, and it indeed worked (with the vcl_hit change explained here and the Host: xxx header). But it may be related also to our setup not passing the correct Host variable from nginx to Varnish, or to trying to purge Varnish from a third server...

As you say in the other ticket "too many edge cases for a black-box recipe user" :smiley:

**Comment by fredvd** [comment]
> As you say in the other ticket "too many edge cases for a black-box recipe user" 😃

And the 'root cause' behind the black-box problem and recipe maintenance: as soon as you have debugged your way through varnishlog and learned enough to understand most edge cases in the recipe and >your< varnish/nginx/apache/Plone stack, you no longer need the recipe because you can roll your own specialised varnish.vcl and all the switches so carefully crafted by others who went down this same road start to work against you.

I only found out last week from the code that sick/grace and probing was already in the recipe, but I need to set 2 variables (grace-sick & grace healthy) in the recipe config to enable extra template snippets for health probing as well.

**Comment by erral** [comment]
I made a test with the vcl_hash thing. With that change I can purge without the need of the Host header.

So I would be in favour of doing it the default value in the recipe.

**Comment by mauritsvanrees** [comment]
The stuff that Fred did was merged and released as 6.0.0b1.

@erral Does this mean your PR can be closed?

**Comment by erral** [comment]
If @fredvd's change was already merged, we can close this.

**Comment by erral** [comment]
Sorry for the noise. The PR addressed the way the generated vcl file handled the PURGE requests, but in the discussion we talked about the use of the vcl_hash function.

Anyway the PR is not anymore valid because of the support of only Varnish 6, so I will check if my PR is valid anymore and prepare another PR if needed.

**Comment by erral** [comment]
I have checked the new recipe *without* my changes and it purges correctly the cached urls, so my PR is not needed anymore.

**Pull request closed without merging**
