### PR TITLE
github actions

### PR DESCRIPTION
**Pull request by mamico**
see #90

* [x] add tox
* [x] add github actions (test + lint)
* [x] make tests happy
* [ ] add coverage/coveralls
* [x] cleanup (travis configs, badges, ...)

`tox -e py27` works locally, I don't know if it is a good idea to work so that it can also work on github.

### CODE REVIEW

**Comment by fredvd** [comment]
@mamico Thanks for picking this up.  the challenge with Python 2.7 support will be that github itself is deprecating or already has deprecated generic 2.7 support.   Looking up.. has removed:   https://github.com/actions/setup-python/issues/672

So I'm not sure if we should still put the effor here in Python 2.7.   Could Plone/meta help here as well?

**Comment by mauritsvanrees** [comment]
I would say: drop 2.7 support.  Only support 3.8-3.11.  Testing on 3.8 and 3.11 should be enough.  Or start with only one Python.

We would be dropping support in a bugfix release, but that is because we chose to have the package version start with the Varnish version we support.

**Comment by mauritsvanrees** [comment]
I am not sure if coverage will work.  I think I have seen problems years ago when I tried it on a buildout recipe, and lots of code was not picked up because coverage could not detect that this code was being run.  Your mileage may vary.

For me, coverage is not needed.  But sure, if it can be done, then it can be used to keep the coverage at a minimum level.

**Comment by mamico** [comment]
@mauritsvanrees I confirm your experience. IMO the coverage does not detect code that is executed during system calls (ie `system(bin/buildout)`).

We can re-evaluate this in the future, for now I'll stop here.

**Review by mauritsvanrees — APPROVED** [review]
Thanks a lot!

**Comment by mauritsvanrees** [comment]
I have released 6.0.11 with this.
I needed to remove the towncrier config first, because it was not working.  See commit 9fea8084482fd79bb638d97977e297f04d9696c2.  You can restore it now if you want, and add a `news/.gitkeep` file, and some lines of explanation in `CHANGES.rst`.

**Pull request merged**
