### PR TITLE
Varnish 5

### PR DESCRIPTION
**Pull request by jensens**
minor tweaks to make latest varnish happy

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
The master branch should be merged in here, or this branch rebased on master.
But even then, I guess Travis will fail in the same way as #54.

**Comment by cleberjsantos** [comment]
This becomes invalid due to #56 ?

**Comment by mauritsvanrees** [comment]
Hah, this is shown as 'merged' because your PR #56 includes all the commits in here I guess. :-) Well, that's fine. This PR can now indeed be ignored.

**Comment by cleberjsantos** [comment]
:+1:

**Pull request merged**
