### PR TITLE
fix cookie-pass default value

### PR DESCRIPTION
**Pull request by petschki**
see #49 

@mauritsvanrees maybe we can go 2.0 final in the next release?

### CODE REVIEW

**Comment by petschki** [comment]
@mauritsvanrees @jensens somebody knows whats with this `six` version conflict on travis?

**Comment by mauritsvanrees** [comment]
I have fixed the `six` issue on master.
I have rebased your branch on master and force pushed it. Let's see what Travis says now.

**Comment by mauritsvanrees** [comment]
Merged.

@jensens Anything against a 2.0 final? It's about time I would say. :-)

**Comment by jensens** [comment]
> @jensens Anything against a 2.0 final? It's about time I would say. :-)

its overdue!

**Comment by mauritsvanrees** [comment]
I have released version 2.0 with this. Enjoy!

**Pull request merged**
