### PR TITLE
vcl_synth

### PR DESCRIPTION
**Pull request by mamico**
Add vcl_synth options to insert arbitrary vcl

### CODE REVIEW

**Review by fredvd — APPROVED** [review]
👍🏼

**Comment by fredvd** [comment]
@mamico  Minor detail, but the vcl_synth option should also be mentioned in the README.rst 😉

**Review by jensens — APPROVED** [review]

**Comment by mamico** [comment]
> @mamico Minor detail, but the vcl_synth option should also be mentioned in the README.rst 😉

@fredvd there is https://github.com/collective/plone.recipe.varnish/pull/99/files#diff-7b3ed02bc73dc06b7db906cf97aa91dec2b2eb21f2d92bc5caa761df5bbc168fR311 ... at the same level of detail as the others ;)

**Comment by fredvd** [comment]
@mamico  I totally overlooked it.  did the review on mobile. I'll merge then.

**Pull request merged**
